# Generated by Django 6.0.1 on 2026-02-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepmind', '0002_futureupdate_projectinfo_teammember_delete_actividad'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Captura de App StepMind', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional de la captura')),
                ('imagen', models.ImageField(upload_to='app_screenshots/')),
                ('activa', models.BooleanField(default=True, help_text='Mostrar esta captura en la página principal')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Captura de App',
                'verbose_name_plural': 'Capturas de App',
            },
        ),
    ]
