# Generated by Django 6.0.1 on 2026-02-02 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepmind', '0003_appscreenshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Nombre de esta galería (ej: 'Tour Principal')", max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la galería')),
                ('activa', models.BooleanField(default=True, help_text='Mostrar esta galería en la página principal')),
                ('auto_play', models.BooleanField(default=False, help_text='Reproducción automática')),
                ('intervalo_segundos', models.PositiveIntegerField(default=3, help_text='Segundos entre imágenes (auto-play)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Galería de App',
                'verbose_name_plural': 'Galerías de App',
            },
        ),
        migrations.CreateModel(
            name='AppGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título de esta imagen', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de lo que muestra esta imagen')),
                ('imagen', models.ImageField(upload_to='app_gallery/')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden en la secuencia (0 = primera)')),
                ('activa', models.BooleanField(default=True, help_text='Mostrar esta imagen en la galería')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('galeria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='stepmind.appgallery')),
            ],
            options={
                'verbose_name': 'Imagen de Galería',
                'verbose_name_plural': 'Imágenes de Galería',
                'ordering': ['orden', 'fecha_creacion'],
            },
        ),
    ]
