# Generated by Django 6.0.1 on 2026-02-02 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepmind', '0004_appgallery_appgalleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='StepMind APK', max_length=100)),
                ('version', models.CharField(help_text='Versión de la app (ej: 1.0.0)', max_length=20)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de esta versión')),
                ('archivo_apk', models.FileField(help_text='Archivo APK para descargar', upload_to='apks/')),
                ('activa', models.BooleanField(default=True, help_text='Mostrar esta versión para descarga')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('descargas', models.PositiveIntegerField(default=0, help_text='Número de descargas')),
            ],
            options={
                'verbose_name': 'APK de StepMind',
                'verbose_name_plural': 'APKs de StepMind',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
